### ISSUE TITLE
Bars width and image size

### ISSUE THREAD

**Issue by kalatchev** [Tagliatti/NetBarcode#14]
Hi,

I am trying to figure out how can I set widths of bars (wide and thin) and based on that, to calculate what width barcode will be. As I unerstand, now barcodes are scaled to desired width. What I need is to have fixed bars width and variable width of generated image.

Thanks in advance.

**Comment by kalatchev** [comment]
Hi @Tagliatti ,

Thanks for your answer. I think I was misunderstood. What I asked is if it's possible to control bars width (thin and/or wide) and to have them with fixed values. Let say I have to encode two strings: "ABCD" and "ABCDEFGH". I would like to make bars with fixed width and as a result I should have something like this:

![image](https://user-images.githubusercontent.com/10154711/90995483-c7ffc400-e5c4-11ea-8c88-f10f4b98f980.png)

Later I took a look at the code and realized that bars width are calculated dynamically to stretch the result image. In all construcors, I see `_autoSize = false;`, and later, when barcode is drawn we have
```C#
   if (_autoSize)
            {
                _width = barWidth * _encodedData.Length;

                _height = _width / aspectRatio;
            }
...
   var iBarWidth = _width / _encodedData.Length;
...
```
In did not investigate whole the code, but what I see is that bars width will be calculated and then the barcode will be stretched. And here what I have as a result:

![image](https://user-images.githubusercontent.com/10154711/90996832-8c66f900-e5c8-11ea-93f9-b7d3bd0b21de.png)

The point is that **the thin and wide bars in first and second case has different widths**. From now on, many issues with scanners can occur. So finally, what I would like to have is **to set height of the barcode and width of the bars**, and **to get an image with final width as wide as needed** like my first example (made with https://www.morovia.com/free-online-barcode-generator/ where the aproach is like mine).

**Comment by Tagliatti** [comment]
@kalatchev @nomaddamon added this feature in version 1.4

**Comment by kalatchev** [comment]
Thanks @Tagliatti !
