### ISSUE TITLE
barcode.SaveImage does not save image

### ISSUE THREAD

**Issue by jezile** [Tagliatti/NetBarcode#19]
Hi,

Below code does not save image nor returning any exception:
```
Dim barcode = New Barcode("123456789", TYPE.CODE128)
barcode.SaveImage("test.png", SaveTypes.PNG)
```

Using NetBarcode 1.4.0 installed via NuGet

Also Looks like docs are not up to date, `barcode.SaveImageFile` does not exist.

Regards,

**Comment by Tagliatti** [comment]
Hello, as you can check here https://github.com/Tagliatti/NetBarcode/blob/86cfc62c40c4cabb8a9805d062d33307664fc31b/NetBarcode/Barcode.cs#L468 the function exists. I'm not sure, but VB is not compatible with .NET Core.
The requirements for rolling lib are, .NET Standard 2, libc6-dev and libgdiplus.
