### ISSUE TITLE
Codabar invert lettter C and B

### ISSUE THREAD

**Issue by FedeC87p** [Tagliatti/NetBarcode#20]
Hi, 

when I try to generate a Codabar with C letter, but when I Scan the code I read letter B instead of C

Example:

var barcode = new Barcode("C123456789C", NetBarcode.Type.Codabar, true, width, height);
barcodeImage = barcode.GetBase64Image();

when I view the image in a tag <img> with embded data I view in the image data C123456789C, but when I scan the barcode the result is B123456789B 

So I try to invert the code with:

var barcode = new Barcode("B123456789B", NetBarcode.Type.Codabar, true, width, height);
barcodeImage = barcode.GetBase64Image();

and now when I scan the barcode the result is C123456789C

**Comment by Tagliatti** [comment]
Hello, this week I'm going to check this out.  Thanks

**Comment by Tagliatti** [comment]
@FedeC87p using your sample code I tested on these two sites SITE1, SITE2, on the phone with the app for IOS QR Reader, and they all showed me the same result below. Are you testing on a reader device? 

![image](https://user-images.githubusercontent.com/4907036/118702195-ff656f00-b7ea-11eb-806a-8176c1d986bf.png)
![image](https://user-images.githubusercontent.com/4907036/118702217-04c2b980-b7eb-11eb-8d05-65b7baf377a2.png)

Barcode
![test](https://user-images.githubusercontent.com/4907036/118702709-a5b17480-b7eb-11eb-895d-a14feda16e9e.png)

**Comment by FedeC87p** [comment]
I try to scan with my android xiaomi redmi 9 with app: QR & Barcode Scanner, and the result is B123456789B

![InkedScreenAndroid_LI](https://user-images.githubusercontent.com/58514549/118766359-9af2f000-b87c-11eb-9ca8-3a16dc75f6df.jpg)

This screen is the result of your barcode posted.


This is the code that I Used and the result is the same with B:

var barcode = new Barcode("C123456789C", NetBarcode.Type.Codabar, true, 221, 78);
barcodeImage = barcode.GetBase64Image();
return "data:image/png;base64," + barcodeImage;


![barcode reader](https://user-images.githubusercontent.com/58514549/118765605-98dc6180-b87b-11eb-87ac-5cd157bda393.PNG)

**Comment by FedeC87p** [comment]
Maybe this value is inverted?

_codabarCode.Add('B', "1010010011");//"101011001011");
_codabarCode.Add('C', "1001001011");//"110101100101");
_codabarCode.Add('b', "1010010011");//"101011001011");
_codabarCode.Add('c', "1001001011");//"110101100101");

**Comment by Tagliatti** [comment]
@FedeC87p Thank you very much for your help, it really was reversed. I also checked each character to make sure I didn't have any more errors. Can you check version 1.4.1 if everything is right?

**Comment by FedeC87p** [comment]
Yes, I try and now it's all right!!!

Thanks!!!!
