### ISSUE TITLE
Support .NET 6 on Linux

### ISSUE THREAD

**Issue by chaimtevel** [Tagliatti/NetBarcode#25]
Hi,

I'm trying to use this library with .NET 6 on a docker alpine image. However I'm running into [this](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only)  issue. Are there plans of swapping out the `System.Drawing` dependencies for one of the [recommended libraries](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only#recommended-action)?

Thanks!

**Comment by Tagliatti** [comment]
Hello, I hadn't seen that they killed System.Drawing.Common, I'll check which lib to use now. 
Thanks for the report.

**Comment by drusellers** [comment]
Hello, @Tagliatti did you make decision on the library? If so, I can try and put a PR together. I need .NET 6 on Linux support.

**Comment by Tagliatti** [comment]
@drusellers I'm having a painting quality problem on image sharp and I still don't know how to solve it, if you can help, on the net6 branch.

**System.Drawing**
![System.Drawing](https://user-images.githubusercontent.com/4907036/167504628-7c3c8624-d9b7-4eca-80e2-624cab5cabc3.jpg)

**ImageSharp**
![ImageSharp](https://user-images.githubusercontent.com/4907036/167504655-1d9d19bf-63e6-4852-86f3-749874f816fd.jpg)
