### ISSUE TITLE
Crashes when no fonts are found. Even if showLabel is set to false.

### ISSUE THREAD

**Issue by greg84** [Tagliatti/NetBarcode#30]
I'm doing this:

`var barcode = new Barcode(barcodeData, Type.Code39, false, 321, 38);`

The application is running in a Linux container with no fonts installed so the `SystemFonts.Collection.Families` collection is empty.

Because of this it crashes with a "Sequence contains no elements" error in Barcode.cs on line 79.

It would be nice if it only checked the fonts when `showLabel` is set to `true`, as otherwise the font is not used.

Could replace First with FirstOrDefault and then crash if font is null before rendering the label?

**Comment by Tagliatti** [comment]
tks @greg84
