### ISSUE TITLE
Change Label font size 

### ISSUE THREAD

**Issue by zinmar509** [Tagliatti/NetBarcode#33]
How to change label font size?

My Bar code is look like this. I want to change to smaller font size.

![image](https://user-images.githubusercontent.com/72735667/174830894-9e90f125-8dcd-4464-91c1-55ef2bc99885.png)

produce with this code.

 var bc = new Barcode(stringdata, NetBarcode.Type.Code128,true,170,50));

**Comment by Tagliatti** [comment]
Hi, this is a simple example of how to do it:
```
var defaultFont = SystemFonts.Collection.Families.FirstOrDefault();
var labelFont = SystemFonts.CreateFont(defaultFont.Name, 5, FontStyle.Bold);
var bc = new Barcode(stringdata,true,170,50, labelFont);
```
