### ISSUE TITLE
Offer - Variable bar length and better label positioning for EAN barcodes

### ISSUE THREAD

**Issue by savissimo** [Tagliatti/NetBarcode#7]
While they are working for scan readers, the barcodes generated for EAN codes don't comply with the industry standard representation (with longer bars where the markers are, and "broken" label - see https://en.wikipedia.org/wiki/International_Article_Number#/media/File:EAN13.svg for an example). 

I appreciate the elegance of your solution for rendering the barcode, and as I said there is no practical or functional necessity to improve the rendering, but it would be cool to obtain an image that is 100% similar to what you would find on a commercial product package. 

I offer to implement a better rendering for EAN-8 and EAN-13 through polymorphism. Is this something you would be interested in adding, or would you rather keep it simpler in your library?

**Comment by Tagliatti** [comment]
If you develop this functionality I can analyze, I accept any contribution. It is only you send pull request that we enter into an agreement for the code. 😉

**Comment by savissimo** [comment]
Great! I was wondering if you had something against having the feature. I'll be working on it, and I'll send you a pull request when I'm done. Thank you.
