### ISSUE TITLE
How to specify CODE 128A ?

### ISSUE THREAD

**Issue by tdilkie** [Tagliatti/NetBarcode#8]

**Comment by Tagliatti** [comment]
hey bro, sorry for the delay, I did not really realize that there is no way to select the type of code 128, but it automatically selects the type according to the text input, but I will create a way to select type A, B or C.

**Comment by Tagliatti** [comment]
Update to [1.0.7](https://github.com/Tagliatti/NetBarcode/commit/82a7ce2df982ecab17f379f0d61170eec99fb5b4)
